### ISSUE TITLE
VM instantiation using Buffer (as apposed to string)

### ISSUE THREAD

**Issue by tpmccallum** [second-state/ssvm-napi#17]
At present the [VM instantiation is coded to accept a hex string](https://github.com/second-state/ssvm-napi/blob/master/ssvmaddon.cc#L32).

Joey is storing the native wasm executables and [instantiating the VM using Buffer](https://github.com/second-state/wasm-joey/blob/master/src/server.js#L505) with the belief that SSVM no longer needs to convert native wasm into hex string any more.

When instantiating a VM instance, Joey gets the following error `(node:22715) UnhandledPromiseRejectionWarning: Error: wasm file expected`

Can SSVM be changed to accept Buffer instead of string?

Thank you

**Comment by hydai** [comment]
We've released [ssvm@0.3.4](https://www.npmjs.com/package/ssvm/v/0.3.4) npm package, which supports vm instantiation using Buffer(Uint8Array).
