### ISSUE TITLE
missing releases for arm64

### ISSUE THREAD

**Issue by proohit** [second-state/ssvm-napi#75]
I'm trying to install SSVM on RPiOS with npm, which throws a 404 on [https://github.com/second-state/ssvm-napi/releases/download/0.7.3/ssvm-linux-arm.tar.gz](https://github.com/second-state/ssvm-napi/releases/download/0.7.3/ssvm-linux-arm.tar.gz). I checked and there are no releases for ARM for versions 0.7.2 and 0.7.3.

Here are the installation logs (shortened bc of failed source compilation)
```
> ssvm@0.7.3 install /home/pi/Documents/nodejs-rust/smartcore-ssvm/node_modules/ssvm
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/second-state/ssvm-napi/releases/download/0.7.3/ssvm-linux-arm.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for ssvm@0.7.3 and node@14.16.1 (node-v83 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/second-state/ssvm-napi/releases/download/0.7.3/ssvm-linux-arm.tar.gz
```
Is there any limitation on which node version can be used?

## Additional info
```
$ node -v
v14.16.1
```
```
$ npm -v
6.14.12
```
```
uname -a
Linux raspberrypi 4.19.57-v7+ #1244 SMP Thu Jul 4 18:45:25 BST 2019 armv7l GNU/Linux
```

**Comment by proohit** [comment]
I'd like to add news to this. I switched to an actual aarch64, Ubuntu OS. This time, I tried manual compilation:
```
make: Entering directory '/home/ubuntu/workspace/nodejs-rust/smartcore-ssvm/node_modules/ssvm/build'
  CXX(target) Release/obj.target/ssvm/src/addon.o
  CXX(target) Release/obj.target/ssvm/src/bytecode.o
  CXX(target) Release/obj.target/ssvm/src/options.o
  CXX(target) Release/obj.target/ssvm/src/ssvmaddon.o
  CXX(target) Release/obj.target/ssvm/src/utils.o
  CXX(target) Release/obj.target/ssvm/ssvm-core/lib/aot/compiler.o
```
... and there it get's stuck. I was monitoring the processes with htop:
![image](https://user-images.githubusercontent.com/46965017/116902357-e1471e80-abef-11eb-9704-b5d9d4ed1c65.png)
At first, the `cc1plus` program used 99% CPU, but after some time it went down to like 5%, as shown in the image. Also, the Memory seems to be constantly full. May this be the reason of stuck compilation?

Or am I just being impatient, being a spoiled new developer? :)
## env
```
$ uname -a
Linux raspberry 5.4.0-1028-raspi #31-Ubuntu SMP PREEMPT Wed Jan 20 11:30:45 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```
Raspberry Pi 3b+
Ubuntu 20.04 Server

**Comment by proohit** [comment]
Are there any news or ETAs on this..?

**Comment by hydai** [comment]
> I'm trying to install SSVM on RPiOS with npm, which throws a 404 on https://github.com/second-state/ssvm-napi/releases/download/0.7.3/ssvm-linux-arm.tar.gz. I checked and there are no releases for ARM for versions 0.7.2 and 0.7.3.
> 

Sorry for missing the arm pre-built binary. We will add the pre-built binary once we have an arm machine.



> I'd like to add news to this. I switched to an actual aarch64, Ubuntu OS. This time, I tried manual compilation:
> At first, the `cc1plus` program used 99% CPU, but after some time it went down to like 5%, as shown in the image. Also, the Memory seems to be constantly full. May this be the reason of stuck compilation?

And it looks like your memory is not enough to build. So the compilation process is killed by OS when the memory run out. Maybe you can add some swap to make the compilation work.
